Merge #13530: bench: Add missing pow.h header
cec84c2f1a359676ac4d206f10ee936d4d7db9b5 bench: Add missing pow.h header (Wladimir J. van der Laan)

Pull request description:

  Fix a build error introduced in #13219.

  ```
  .../bitcoin/src/bench/block_assemble.cpp:42:13:error: use of undeclared identifier 'CheckProofOfWork'
      while (!CheckProofOfWork(block->GetHash(), block->nBits, Params().GetConsensus())) {
  ```

Tree-SHA512: 6ef78011fd7bd82859530b2676ba533b15db6c753cb84a1286b7e26ed6f3d2064769e42900b2479fe6c460411f742e2baed716db5eac06d3bc455e08c290a087