fix: add missing changes and adjust fee rate to fix bitcoin/bitcoin#25379
Otherwise this error appears:

    test_framework.authproxy.JSONRPCException: min relay fee not met, 25500 < 30332 (-26)